



typedef struct _COMMAND_MESSAGE
{
	BOOLEAN bIsSuccess;
	WCHAR Volume[100];
	WCHAR Name[300];
	WCHAR Extension[32];
	WCHAR FinalComponent[256];
	WCHAR ParentDir[256];
	WCHAR FileOpear[32];
	WCHAR ShowMsg[MAX_SHOWMSG];
} COMMAND_MESSAGE,*PCOMMAND_MESSAGE;

typedef struct _USER_COMMAND_MESSAGE
{
	FILTER_MESSAGE_HEADER MsgHeader;
	COMMAND_MESSAGE CommandMsg;
	OVERLAPPED Ovlp;
} USER_COMMAND_MESSAGE,*PUSER_COMMAND_MESSAGE;


typedef struct _REPLY_MSG
{
	BOOLEAN bIsSuccess;
} REPLY_MSG,*PREPLY_MSG;

typedef struct _USERCOMMAND_MESSAGE_REPLAY
{
	FILTER_REPLY_HEADER ReplayHeader;
	REPLY_MSG ReplyMsg;

} USERCOMMAND_MESSAGE_REPLAY,*PUSERCOMMAND_MESSAGE_REPLAY;


typedef struct _MSG_THREAD_CONTEXT
{
	HANDLE hPort;
	HANDLE hCompletion;
} MSG_THREAD_CONTEXT, *PMSG_THREAD_CONTEXT;


